<?php
require('view_begin.php');
?>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Year</th>
      <th>Birhdate</th>
      <th>Birthplace</th>
      <th>County</th>
      <th>Motivation</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><?=$name?></td>
        <td><?=$category?></td>
        <td><?=$year?></td>
        <td><?=$birthdate?></td>
        <td><?=$birthplace?></td>
        <td><?=$county?></td>
        <td><?=$motivation?></td>
      </tr>

  </tbody>
</table>

<?php
require('view_end.php');
?>
